### PR TITLE
add yarn to engines

### LINKED ISSUE #29: Incompatible with Node 11.8.0
the build folder is missing in `node_modules/upath/` which breaks `chokidar` which breaks a lot of other packages

### PR DESCRIPTION
**Pull request by JipSterk**
fixes #29

### CODE REVIEW

**Comment by anodynos** [comment]
Thanks for the PR :-)

**Comment by itaykomemy** [comment]
@JipSterk 
This breaks builds for a lot of projects with yarn < 1, our build specifically...
If I understand correctly you could change it to
`{..."yarn": "*"}` with the same effect
Am I correct?

**Comment by anodynos** [comment]
Sorry to hear @JipSterk - I'll fix it

**Comment by anodynos** [comment]
@JipSterk fixed & published :-)

**Comment by itaykomemy** [comment]
@anodynos 
thats awesome! thanks!

**Comment by egoist** [comment]
hmm I guess it will produce a warning when `yarn` is not available on your machine?

**Pull request merged**
